### ISSUE TITLE
Høstestatus blir ikke oppdatert når det er feil og høstingen startes manuelt via admin

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-harvest-admin#128]
Feilmelding ble vist i høstestatus for datasettkatalogen til Digdir. Startet høsting manuelt for å se om det kun var en midlertidig feil og da ble ikke høstestatus oppdatert. Den ble stående med status "in-progress".

Feilmelding:  (org.apache.jena.riot.RiotException: [line: 568, col: 57] Bad character in IRI (space): <[space]...>

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/fdk-harvest-admin/commit/a33e7e881c90cbcbc64fdd3b7fb3df333fd225c5
