### ISSUE TITLE
Kontrakttest for fdk-harvest-admin

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-harvest-admin#43]
Ta utgangspunkt i
a-frontend-service
a-backend-service

og verifiser at de ulike tjenestene har en specc fil.
Deretter skal vi skrive kontrakttester/featuretester for den enkelte tjenesten.

Implementere kontrakttest/featurestest for tjenesten:
fdk-harvest-admin

**Comment by NilsOveTen** [comment]
løses av #87
