### ISSUE TITLE
Støtte flere versjoner av en gitt spesifikasjon

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-harvest-admin#61]
- [ ] Må støtte dcat-ap-no 1.1 og dcat-ap-no 2.0

**Comment by KjerstiSteien** [comment]
@KurtStian @NilsOveTen hva er status her? Støtter vi flere versjoner av spesifikasjonene nå? Hvilke versjoner mangler eventuelt?

**Comment by NilsOveTen** [comment]
Vi støtter begge versjonene, men sikkert bare delvis. @KurtStian har snakket om å lage en oversikt over hvilke felt som støttes og ikke, men tviler på at det er en enkel jobb.

Det er også forskjell på hva vi støtter i høsting og hva vi støtter i registrering

**Comment by KjerstiSteien** [comment]
Jeg foreslår at vi beskriver dette som et eget issue dersom vi ønsker å løse dette. Denne saken inneholder ikke viktig informasjon
