### ISSUE TITLE
Få feilmeldinger til å dukke opp i error-reporting i GCP

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-harvest-admin#96]
https://cloud.google.com/error-reporting/docs/setup/go

**Comment by oyvindis** [comment]
@NilsOveTen Hadde det ikke vært bedre å få alle logger fra alle pods inn i Grafana, da har vi det tilgjengelig i Grafana-dashboardet?

**Comment by NilsOveTen** [comment]
> @NilsOveTen Hadde det ikke vært bedre å få alle logger fra alle pods inn i Grafana, da har vi det tilgjengelig i Grafana-dashboardet?

@valosnah bruker nå error-reporting for å følge med i GCP, i første omgang tenker jeg at det er best at denne oppfører seg som de fleste andre pod'ene

Om vi i fremtiden egentlig bare bruker Grafana for å følge med på loggene så kan vi sikkert droppe å bry oss om error-reporting i GCP, men etter som jeg forstår så er vi ikke der nå

**Comment by oyvindis** [comment]
Snakket med Jeff og fikk det litt mer oppklart siden jeg ikke skjønte det helt. Det er bare metrikker vi har satt opp å vise i Grafana. Ellers har vi alle logger i GCP, og det er ikke poeng å duplisere det til Grafana. Så da bør vi altså bare bruke GCP og ikke vise det i Grafana som jeg foreslo.

Opprinnelig det du skrev, error-reporting i GCP, det burde du vel da allerede ha tilgjenglig, så lenge applikasjonen faktisk logger feil?

**Comment by valosnah** [comment]
Feilemeldinger må formateres på et spesifikt vis for at de skal kunne plukkes opp av Error-reporting tjenesten.
https://cloud.google.com/error-reporting/docs/formatting-error-messages

**Comment by NilsOveTen** [comment]
Kort fortalt trenger vi å legge til stack trace i feilmeldingene, alt annet er satt opp korrekt i forhold til GCP

Sannsynligvis en enkel måte å få tak i stack trace i GO, men jeg orket ikke finne ut av det der og da. Derav issue
